


import scrapy


class DarsacomItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    pass

'''
class DarsacomItem(Item):
    id = Field()
    id_erp = Field()
    idMarca = Field()
    seller_id = Field()
    sku = Field()
    nombreProducto = Field()
    modelo = Field()
    dimension = Field()
    peso = Field()
    peso_volumetrico = Field()
    ancho = Field()
    largo = Field()
    alto = Field()
    apilable = Field()
    maxApilable = Field()
    propAncho = Field()
    propAlto = Field()
    propLargo = Field()
    ruta = Field()
    pack = Field()
    variantesAgrupadas = Field()
    packPadre = Field()
    margen = Field()
    stock = Field()
    idMedida = Field()
    precio = Field()
    precioReferencia = Field()
    img = Field()
    youtube = Field()
    video = Field()
    descripcion = Field()
    descripcionCorta = Field()
    despacho = Field()
    retiroTienda = Field()
    descuento = Field()
    mostrarHome = Field()
    probador = Field()
    destacado = Field()
    complemento = Field()
    precioComplemento = Field()
    fichaTecnica = Field()
    nombreFicha = Field()
    orientacion = Field()
    delivery = Field()
    idProveedor = Field()
    idioma = Field()
    tag = Field()
    meta_title = Field()
    meta_description = Field()
    actionStore = Field()
    currencyBasePrice = Field()
    saleDecimal = Field()
    criticalStock = Field()
    idCategoria = Field()
    tipoVenta = Field()
    cantidadLote = Field()
    precioUnitario = Field()
    rechazoProducto = Field()
    publicado = Field()
    created_at = Field()
    updated_at = Field()
    deleted_at = Field()
    published_at = Field()
    centry_id = Field()
    cat_id = Field()
    cat_nombre = Field()
    cat_alias = Field()
    cat_ruta = Field()
    cat_img = Field()
    cat_banner = Field()
    marca = Field()
'''